from __future__ import annotations

from maintenancetool.cli import runtime_commands as _runtime_commands
from maintenancetool.cli import runtime_support as _runtime_support

build_runtime_app = _runtime_commands.build_runtime_app
launch_default_launcher = _runtime_commands.launch_default_launcher
ADVANCED_CLI_GUARD_ENABLED = _runtime_support.ADVANCED_CLI_GUARD_ENABLED
DEFAULT_WORKSPACE = _runtime_support.DEFAULT_WORKSPACE
console = _runtime_support.console
is_admin_session = _runtime_support.is_admin_session
_is_windows_runtime = _runtime_support.is_windows_runtime
_print_advanced_cli_blocked = _runtime_support.print_advanced_cli_blocked
_require_advanced_cli = _runtime_support.require_advanced_cli

app = build_runtime_app()
